### PR TITLE
Readme file made

### PR DESCRIPTION
**Pull request by chindrop**
## In milestone 4: Readme made

- How to start the game was given.
- Instructions on how to play the game were given.
- Other information on the project was stated there.

### CODE REVIEW

**Review by christianotieno — CHANGES_REQUESTED** [review]
# Changes Required ⚠️ 
## Hello Team!
- [x] The project looks great. Before we proceed, kindly make sure linter is enabled in this project, and that all checks are passing successfully. Thank you!

If you have any questions of the same, you can reach out to me via Slack.

**Comment by jessicafarias** [comment]
Thanks for your review.
Linter of the project added in the branch game_logic.
👍 😄

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :balloon: 

Hi **TEAM**, you have done a great job :+1: The README is professional, it has instructions on how to play the game :100: You have therefore met the minimum requirement for this project :+1: 

[OPTIONAL]
Kindly make sure linters pass successfully before merging development to master

Go ahead and merge into development :100: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Pull request merged**
