### PR TITLE
Feature/game logic

### PR DESCRIPTION
**Pull request by chindrop**
##In this milestone 3

- We created the logic of the game.
- Classes in player and game files were linked main.rb

### CODE REVIEW

**Review by serdg0 — CHANGES_REQUESTED** [review]
### Hello @jessicafarias @chindrop !

### You have done a great job in this project! Congratulations :fireworks: 

There are some consideration we must address before making your project **outstanding**!
In the list below I point to those considerations:

- [x] No puts/print/chomps outside the main.rb



- [x] When playing, sometimes the board prints false.
error1

- [x] in game.rb, the instance variable `@win_array` is created every time you call the method check_win. A better approach is to create it in initialization.

- [x] `position_override` and `check_win` method in game.rb returns a boolean, and in Ruby, it's a convention to add "?" at the end of the  methods that return a boolean. e.g `position_override?`

- [x] In `main.rb`  you have a parallel process in both of the loops that are inside the `while game.check_win ==  false` . Remember to apply DRY rules as is a mandatory OOP practice.



Kindly address the issues above and submit for another Code Review.

**Happy Coding!** :computer: :nerd_face:
**_Sergio Diaz_**

**Comment by jessicafarias** [comment]
Thanks a lot for your helpful review, @serdg0 
The issues are fixed  🚀

**Comment by pelzolga123** [comment]
# Hi Team,
## You did great work so far :+1: 
Still, there are a few more issues to correct before this milestone can be approved:
* [x] Linter is not checking this Pull Request right now, please kindly change that. Also, it would be great to resolve a conflict you have right now.

* [x] The application should not allow a player to move into an occupied position. Right now it looks like this:
image

* [OPTIONAL] The app allows users to have an empty name or both users can have the same name, so it's better to add a validation to prevent that from happening.

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by jessicafarias** [comment]
Thanks, @pelzolga123 we fix conflicts and Enabled linter.

**Comment by Dandush03** [comment]
# Status: Project Approved

# Great Work 😄 
# Good luck in your next assignment 

## Happy Coding!

**Pull request merged**
